module.exports = {
    //模拟接口调用
    before(app) {
        app.get('/api/user/info' ,function(req, res){
            res.json({
                code:200,
                message:'ok',
                data:{
                    name:'three-idiots',
                    avatar:'http://images2.fanpop.com/image/photos/9400000/avatar-avatar-2009-film-9474591-1280-960.jpg',
                    roles:[1,2,3]
                }
            });
        });
        app.get('/table/visa/list' ,function(req, res){
        res.json({
          code:200,
          message:'ok',
          data:{
            items: [
              {
                "id": 36,
                "title": "快速签证",
                "type": 0,
                "goodsNum": "G01753367369984",
                "stockNum": 0,
                "status": 1,
                "auditStatus": 0,
                "helpPrice": 10,
                "lowHelpPrice": 0,
                "visaPrice": 10,
                "lowVisaPrice": 10,
                "unitDay": 30,
                "stayDay": 0,
                "intoType": 1,
                "disposeDay": 0,
                "isUrgent": 1,
                "isInterview": 0,
                "isDel": 0,
                "auditTime": null,
                "travelRatio": 2200,
                "channelRatio": 2800,
                "terraceRatio": 5000,
                "renewPrice": 0,
                "ctime": "2018-06-30T14:02:50.000+0000",
                "cuser": 1,
                "ltime": "2018-06-30T14:02:50.000+0000",
                "luser": 1
              },
              {
                "id": 35,
                "title": "加急签证",
                "type": 0,
                "goodsNum": "G01649094370524",
                "stockNum": 0,
                "status": 1,
                "auditStatus": 0,
                "helpPrice": 20,
                "lowHelpPrice": 10,
                "visaPrice": 30,
                "lowVisaPrice": 10,
                "unitDay": 0,
                "stayDay": 1,
                "intoType": 0,
                "disposeDay": 1,
                "isUrgent": 1,
                "isInterview": 1,
                "isDel": 0,
                "auditTime": null,
                "travelRatio": 2200,
                "channelRatio": 2800,
                "terraceRatio": 5000,
                "renewPrice": 100,
                "ctime": "2018-06-27T10:12:51.000+0000",
                "cuser": 1,
                "ltime": "2018-06-27T10:12:51.000+0000",
                "luser": 1
              },
              {
                "id": 34,
                "title": "签证续签",
                "type": 0,
                "goodsNum": "G05629686108296",
                "stockNum": 0,
                "status": 2,
                "auditStatus": 0,
                "helpPrice": 10,
                "lowHelpPrice": 10,
                "visaPrice": 10,
                "lowVisaPrice": 10,
                "unitDay": 0,
                "stayDay": 1,
                "intoType": 0,
                "disposeDay": 1,
                "isUrgent": 0,
                "isInterview": 0,
                "isDel": 0,
                "auditTime": null,
                "travelRatio": 0,
                "channelRatio": 0,
                "terraceRatio": 0,
                "renewPrice": 100,
                "ctime": "2018-06-27T07:55:08.000+0000",
                "cuser": 1,
                "ltime": "2018-06-27T07:55:08.000+0000",
                "luser": 1
              },
              {
                "id": 33,
                "title": "普通签证",
                "type": 0,
                "goodsNum": "G07459564523991",
                "stockNum": 0,
                "status": 1,
                "auditStatus": 0,
                "helpPrice": 30,
                "lowHelpPrice": 10,
                "visaPrice": 40,
                "lowVisaPrice": 20,
                "unitDay": 0,
                "stayDay": 6,
                "intoType": 1,
                "disposeDay": 5,
                "isUrgent": 0,
                "isInterview": 1,
                "isDel": 0,
                "auditTime": null,
                "travelRatio": 2200,
                "channelRatio": 2200,
                "terraceRatio": 5600,
                "renewPrice": 50,
                "ctime": "2018-06-27T01:55:24.000+0000",
                "cuser": 1,
                "ltime": "2018-06-27T13:29:38.000+0000",
                "luser": 1
              },
              {
                "id": 32,
                "title": "朝鲜通加急签证",
                "type": 0,
                "goodsNum": "G01589098579314",
                "stockNum": 0,
                "status": 1,
                "auditStatus": 0,
                "helpPrice": 20,
                "lowHelpPrice": 40,
                "visaPrice": 50,
                "lowVisaPrice": 10,
                "unitDay": 60,
                "stayDay": 2,
                "intoType": 1,
                "disposeDay": 2,
                "isUrgent": 1,
                "isInterview": 1,
                "isDel": 0,
                "auditTime": null,
                "travelRatio": 2300,
                "channelRatio": 2700,
                "terraceRatio": 5000,
                "renewPrice": 60,
                "ctime": "2018-06-26T07:36:19.000+0000",
                "cuser": 1,
                "ltime": "2018-06-26T07:36:19.000+0000",
                "luser": 1
              },
              {
                "id": 31,
                "title": "朝鲜签证续签",
                "type": 0,
                "goodsNum": "G09147820550543",
                "stockNum": 0,
                "status": 2,
                "auditStatus": 0,
                "helpPrice": 100,
                "lowHelpPrice": 100,
                "visaPrice": 100,
                "lowVisaPrice": 100,
                "unitDay": 30,
                "stayDay": 7,
                "intoType": 0,
                "disposeDay": 15,
                "isUrgent": 0,
                "isInterview": 0,
                "isDel": 0,
                "auditTime": null,
                "travelRatio": 0,
                "channelRatio": 0,
                "terraceRatio": 0,
                "renewPrice": 100,
                "ctime": "2018-06-25T09:55:51.000+0000",
                "cuser": 1,
                "ltime": "2018-06-26T07:19:16.000+0000",
                "luser": 1
              },
              {
                "id": 30,
                "title": "朝鲜加急签证",
                "type": 0,
                "goodsNum": "G02000396885943",
                "stockNum": 0,
                "status": 1,
                "auditStatus": 0,
                "helpPrice": 200,
                "lowHelpPrice": 100,
                "visaPrice": 2000,
                "lowVisaPrice": 300,
                "unitDay": 90,
                "stayDay": 20,
                "intoType": 0,
                "disposeDay": 30,
                "isUrgent": 1,
                "isInterview": 1,
                "isDel": 0,
                "auditTime": null,
                "travelRatio": 2500,
                "channelRatio": 2500,
                "terraceRatio": 5000,
                "renewPrice": 400,
                "ctime": "2018-06-23T23:34:46.000+0000",
                "cuser": 1,
                "ltime": "2018-06-26T07:19:35.000+0000",
                "luser": 1
              },
              {
                "id": 29,
                "title": "朝鲜普通签证",
                "type": 0,
                "goodsNum": "G01760293283044",
                "stockNum": 0,
                "status": 1,
                "auditStatus": 0,
                "helpPrice": 100,
                "lowHelpPrice": 100,
                "visaPrice": 100,
                "lowVisaPrice": 100,
                "unitDay": 30,
                "stayDay": 30,
                "intoType": 0,
                "disposeDay": 1,
                "isUrgent": 0,
                "isInterview": 0,
                "isDel": 0,
                "auditTime": null,
                "travelRatio": 3500,
                "channelRatio": 3500,
                "terraceRatio": 3000,
                "renewPrice": 100,
                "ctime": "2018-06-23T22:34:43.000+0000",
                "cuser": 1,
                "ltime": "2018-06-23T22:34:43.000+0000",
                "luser": 1
              }
            ]
          }
        });
      });
    }
};

